// products-data.js

// Ánh xạ từ Tên Danh Mục đầy đủ sang slug dùng trong URL
const categorySlugs = {
    'Sữa Tươi': 'sua-tuoi',
    'Rau, Củ, Trái Cây': 'rau-cu-trai-cay',
    'Đồ Uống Giải Khát': 'do-uong-giai-khat',
    'Đồ Uống Có Cồn': 'do-uong-co-con',
    'Thực Phẩm Ăn Liền': 'thuc-pham-an-lien',
    'Gia Vị': 'gia-vi',
    'Trứng - Đậu Hũ': 'trung-dau-hu',
    'Đồ Gia Dụng': 'do-gia-dung',
    'Văn Phòng Phẩm': 'van-phong-pham',
    'Vệ Sinh Cá Nhân': 've-sinh-ca-nhan'
};
const allProducts = [
    { id: 'p1', name: 'Sữa Chua Dâu', category: 'Sữa Tươi', price: 15000, img: 'images/p1.jpg', quantity: 120 },
    { id: 'p2', name: 'Sữa Tươi Tiệt Trùng', category: 'Sữa Tươi', price: 12000, img: 'images/p2.jpg', quantity: 150 },
    { id: 'p3', name: 'Sữa Tươi Không Đường', category: 'Sữa Tươi', price: 11000, img: 'images/p3.jpg', quantity: 90 },
    { id: 'p4', name: 'Sữa Chua Men Probi', category: 'Sữa Tươi', price: 17000, img: 'images/p4.jpg', quantity: 110 },
    { id: 'p5', name: 'Sữa Chua', category: 'Sữa Tươi', price: 18000, img: 'images/p5.jpg', quantity: 80 },
    { id: 'p6', name: 'Sữa Chua Nếp Cẩm', category: 'Sữa Tươi', price: 20000, img: 'images/p6.jpg', quantity: 70 },
    { id: 'p7', name: 'Sữa Tươi Fami', category: 'Sữa Tươi', price: 16000, img: 'images/p7.jpg', quantity: 130 },
    { id: 'p8', name: 'Phô Mai', category: 'Sữa Tươi', price: 25000, img: 'images/p8.jpg', quantity: 60 },
    { id: 'p9', name: 'Sữa Milo', category: 'Sữa Tươi', price: 22000, img: 'images/p9.jpg', quantity: 100 },
    { id: 'p10', name: 'Xoài Keo Vàng', category: 'Rau, Củ, Trái Cây', price: 15000, img: 'images/p10.jpg', quantity: 50 },
    { id: 'p11', name: 'Táo Rockit', category: 'Rau, Củ, Trái Cây', price: 30000, img: 'images/p11.jpg', quantity: 45 },
    { id: 'p12', name: 'Dưa Hấu Giống Nhật', category: 'Rau, Củ, Trái Cây', price: 35000, img: 'images/p12.jpg', quantity: 30 },
    { id: 'p13', name: 'Bắp Cải', category: 'Rau, Củ, Trái Cây', price: 12000, img: 'images/p13.jpg', quantity: 100 },
    { id: 'p14', name: 'Rau Muống', category: 'Rau, Củ, Trái Cây', price: 8000, img: 'images/p14.jpg', quantity: 180 },
    { id: 'p15', name: 'Cải Thảo', category: 'Rau, Củ, Trái Cây', price: 10000, img: 'images/p15.jpg', quantity: 120 },
    { id: 'p16', name: 'Cà Rốt', category: 'Rau, Củ, Trái Cây', price: 12000, img: 'images/p16.jpg', quantity: 90 },
    { id: 'p17', name: 'Khoai Tây', category: 'Rau, Củ, Trái Cây', price: 18000, img: 'images/p17.jpg', quantity: 75 },
    { id: 'p18', name: 'Hành Lý Sơn', category: 'Rau, Củ, Trái Cây', price: 25000, img: 'images/p18.jpg', quantity: 60 },
    { id: 'p19', name: 'Nước Ngọt Coca Cola', category: 'Đồ Uống Giải Khát', price: 15000, img: 'images/p19.jpg', quantity: 200 },
    { id: 'p20', name: 'Nước Ngọt Pepsi', category: 'Đồ Uống Giải Khát', price: 15000, img: 'images/p20.jpg', quantity: 180 },
    { id: 'p21', name: 'Nước Ngọt Fanta', category: 'Đồ Uống Giải Khát', price: 14000, img: 'images/p21.jpg', quantity: 160 },
    { id: 'p22', name: 'Nước Ngọt Sprite', category: 'Đồ Uống Giải Khát', price: 16000, img: 'images/p22.jpg', quantity: 140 },
    { id: 'p23', name: 'Nước Ngọt 7up', category: 'Đồ Uống Giải Khát', price: 15000, img: 'images/p23.jpg', quantity: 150 },
    { id: 'p24', name: 'Nước Ngọt Tea+', category: 'Đồ Uống Giải Khát', price: 17000, img: 'images/p24.png', quantity: 100 },
    { id: 'p25', name: 'Cà Phê', category: 'Đồ Uống Giải Khát', price: 25000, img: 'images/p25.jpg', quantity: 80 },
    { id: 'p26', name: 'Aquafina', category: 'Đồ Uống Giải Khát', price: 10000, img: 'images/p26.jpg', quantity: 300 },
    { id: 'p27', name: 'Nước Ngọt Sting', category: 'Đồ Uống Giải Khát', price: 18000, img: 'images/p27.jpg', quantity: 120 },
    { id: 'p28', name: 'Bia Ruby', category: 'Đồ Uống Có Cồn', price: 40000, img: 'images/p28.jpg', quantity: 50 },
    { id: 'p29', name: 'Bia Chai', category: 'Đồ Uống Có Cồn', price: 35000, img: 'images/p29.jpg', quantity: 60 },
    { id: 'p30', name: 'Bia 333', category: 'Đồ Uống Có Cồn', price: 38000, img: 'images/p30.jpg', quantity: 70 },
    { id: 'p31', name: 'Bia Sapporo', category: 'Đồ Uống Có Cồn', price: 50000, img: 'images/p31.jpg', quantity: 40 },
    { id: 'p32', name: 'Bia Hà Nội', category: 'Đồ Uống Có Cồn', price: 22000, img: 'images/p32.png', quantity: 90 },
    { id: 'p33', name: 'Bia Heiniken', category: 'Đồ Uống Có Cồn', price: 45000, img: 'images/p33.jpg', quantity: 80 },
    { id: 'p34', name: 'Bia Budweiser', category: 'Đồ Uống Có Cồn', price: 40000, img: 'images/p34.jpg', quantity: 70 },
    { id: 'p35', name: 'Bia Leffe', category: 'Đồ Uống Có Cồn', price: 60000, img: 'images/p35.png', quantity: 30 },
    { id: 'p36', name: 'Bia Tiger', category: 'Đồ Uống Có Cồn', price: 25000, img: 'images/p36.jpg', quantity: 100 },
    { id: 'p37', name: 'Tobbokki Miwon', category: 'Thực Phẩm Ăn Liền', price: 25000, img: 'images/p37.png', quantity: 80 },
    { id: 'p38', name: 'Cháo Thịt Bằm', category: 'Thực Phẩm Ăn Liền', price: 15000, img: 'images/p38.png', quantity: 150 },
    { id: 'p39', name: 'Mì Lẩu Thái', category: 'Thực Phẩm Ăn Liền', price: 18000, img: 'images/p39.png', quantity: 120 },
    { id: 'p40', name: 'Mì Kokomi', category: 'Thực Phẩm Ăn Liền', price: 16000, img: 'images/p40.jpg', quantity: 130 },
    { id: 'p41', name: 'Mì Cung Đình', category: 'Thực Phẩm Ăn Liền', price: 17000, img: 'images/p41.jpg', quantity: 110 },
    { id: 'p42', name: 'Mì Xào Koreno', category: 'Thực Phẩm Ăn Liền', price: 14000, img: 'images/p42.jpg', quantity: 90 },
    { id: 'p43', name: 'Bún Ốc Tươi', category: 'Thực Phẩm Ăn Liền', price: 20000, img: 'images/p43.jpg', quantity: 70 },
    { id: 'p44', name: 'Mì Hảo Hảo', category: 'Thực Phẩm Ăn Liền', price: 12000, img: 'images/p44.jpg', quantity: 250 },
    { id: 'p45', name: 'Phở Thịt Gà', category: 'Thực Phẩm Ăn Liền', price: 25000, img: 'images/p45.jpg', quantity: 60 },
    { id: 'p46', name: 'Dầu Ăn Neptune', category: 'Gia Vị', price: 45000, img: 'images/p46.png', quantity: 80 },
    { id: 'p47', name: 'Nước Mắm', category: 'Gia Vị', price: 22000, img: 'images/p47.jpg', quantity: 110 },
    { id: 'p48', name: 'Hạt Nêm', category: 'Gia Vị', price: 18000, img: 'images/p48.png', quantity: 90 },
    { id: 'p49', name: 'Mayonaise', category: 'Gia Vị', price: 35000, img: 'images/p49.png', quantity: 70 },
    { id: 'p50', name: 'Nước Tương', category: 'Gia Vị', price: 15000, img: 'images/p50.jpg', quantity: 100 },
    { id: 'p51', name: 'Mì Chính', category: 'Gia Vị', price: 15000, img: 'images/p51.jpg', quantity: 85 },
    { id: 'p52', name: 'Sa Tế', category: 'Gia Vị', price: 12000, img: 'images/p52.jpg', quantity: 65 },
    { id: 'p53', name: 'Gói Lẩu Thái', category: 'Gia Vị', price: 60000, img: 'images/p53.jpg', quantity: 40 },
    { id: 'p54', name: 'Bột Canh', category: 'Gia Vị', price: 14000, img: 'images/p54.png', quantity: 95 },
    { id: 'p55', name: 'Tàu Hũ Trứng', category: 'Trứng - Đậu Hũ', price: 8000, img: 'images/p55.jpg', quantity: 120 },
    { id: 'p56', name: 'Trứng Gà Quê', category: 'Trứng - Đậu Hũ', price: 15000, img: 'images/p56.jpg', quantity: 180 },
    { id: 'p57', name: 'Tàu Hũ Thanh', category: 'Trứng - Đậu Hũ', price: 10000, img: 'images/p57.png', quantity: 90 },
    { id: 'p58', name: 'Tàu Hũ Ky', category: 'Trứng - Đậu Hũ', price: 9000, img: 'images/p58.jpg', quantity: 70 },
    { id: 'p59', name: 'Tàu Hũ Mềm', category: 'Trứng - Đậu Hũ', price: 11000, img: 'images/p59.jpg', quantity: 110 },
    { id: 'p60', name: 'Trứng Gà Ác', category: 'Trứng - Đậu Hũ', price: 20000, img: 'images/p60.jpg', quantity: 60 },
    { id: 'p61', name: 'Trứng Cút', category: 'Trứng - Đậu Hũ', price: 10000, img: 'images/p61.jpg', quantity: 150 },
    { id: 'p62', name: 'Đậu Hũ Rong Biển', category: 'Trứng - Đậu Hũ', price: 13000, img: 'images/p62.jpg', quantity: 80 },
    { id: 'p63', name: 'Đậu hũ thối', category: 'Trứng - Đậu Hũ', price: 8000, img: 'images/p63.jpg', quantity: 50 },
    { id: 'p64', name: 'Khay Đá', category: 'Đồ Gia Dụng', price: 12000, img: 'images/p64.jpg', quantity: 70 },
    { id: 'p65', name: 'Chảo Đáy Nông', category: 'Đồ Gia Dụng', price: 35000, img: 'images/p65.jpg', quantity: 40 },
    { id: 'p66', name: 'Màng Bọc Thực Phẩm', category: 'Đồ Gia Dụng', price: 7000, img: 'images/p66.jpg', quantity: 180 },
    { id: 'p67', name: 'Bình Giữ Nhiệt', category: 'Đồ Gia Dụng', price: 20000, img: 'images/p67.png', quantity: 60 },
    { id: 'p68', name: 'Khăn Sợi Mềm', category: 'Đồ Gia Dụng', price: 15000, img: 'images/p68.jpg', quantity: 130 },
    { id: 'p69', name: 'Nồi Một Tay', category: 'Đồ Gia Dụng', price: 40000, img: 'images/p69.png', quantity: 35 },
    { id: 'p70', name: 'Móc Quần Áo', category: 'Đồ Gia Dụng', price: 5000, img: 'images/p70.jpg', quantity: 200 },
    { id: 'p71', name: 'Găng Tay', category: 'Đồ Gia Dụng', price: 7000, img: 'images/p71.jpg', quantity: 150 },
    { id: 'p72', name: 'Ổ Điện', category: 'Đồ Gia Dụng', price: 25000, img: 'images/p72.jpg', quantity: 80 },
    { id: 'p85', name: 'Giấy Ăn', category: 'Đồ Gia Dụng', price: 15000, img: 'images/p85.jpg', quantity: 190 },
    { id: 'p73', name: 'Bút Bi Thiên Long', category: 'Văn Phòng Phẩm', price: 8000, img: 'images/p73.jpg', quantity: 250 },
    { id: 'p74', name: 'Bút Dạ', category: 'Văn Phòng Phẩm', price: 5000, img: 'images/p74.jpg', quantity: 180 },
    { id: 'p75', name: 'Bút Chì', category: 'Văn Phòng Phẩm', price: 6000, img: 'images/p75.jpg', quantity: 200 },
    { id: 'p76', name: 'Tẩy', category: 'Văn Phòng Phẩm', price: 2000, img: 'images/p76.jpg', quantity: 300 },
    { id: 'p77', name: 'Băng Keo', category: 'Văn Phòng Phẩm', price: 10000, img: 'images/p77.jpg', quantity: 120 },
    { id: 'p78', name: 'Bút Xóa Kéo', category: 'Văn Phòng Phẩm', price: 15000, img: 'images/p78.jpg', quantity: 90 },
    { id: 'p79', name: 'Đồng Hồ', category: 'Văn Phòng Phẩm', price: 25000, img: 'images/p79.jpg', quantity: 50 },
    { id: 'p80', name: 'Bàn Xếp', category: 'Văn Phòng Phẩm', price: 30000, img: 'images/p80.png', quantity: 30 },
    { id: 'p81', name: 'Keo Dán', category: 'Văn Phòng Phẩm', price: 4000, img: 'images/p81.jpg', quantity: 150 },
    { id: 'p82', name: 'Nước Súc Miệng', category: 'Vệ Sinh Cá Nhân', price: 25000, img: 'images/p82.jpg', quantity: 100 },
    { id: 'p83', name: 'Dầu Gội', category: 'Vệ Sinh Cá Nhân', price: 45000, img: 'images/p83.png', quantity: 80 },
    { id: 'p84', name: 'Kem Đánh Răng', category: 'Vệ Sinh Cá Nhân', price: 25000, img: 'images/p84.jpg', quantity: 120 },
    { id: 'p86', name: 'Kem Rửa Mặt', category: 'Vệ Sinh Cá Nhân', price: 55000, img: 'images/p86.jpg', quantity: 70 },
    { id: 'p87', name: 'Sữa Rửa Tay', category: 'Vệ Sinh Cá Nhân', price: 30000, img: 'images/p87.jpg', quantity: 90 },
    { id: 'p88', name: 'Xịt Khử Mùi', category: 'Vệ Sinh Cá Nhân', price: 60000, img: 'images/p88.jpg', quantity: 60 },
    { id: 'p89', name: 'Mặt Nạ', category: 'Vệ Sinh Cá Nhân', price: 10000, img: 'images/p89.jpg', quantity: 110 },
    { id: 'p90', name: 'Bàn Chải', category: 'Vệ Sinh Cá Nhân', price: 12000, img: 'images/p90.jpg', quantity: 140 },
];
allProducts.forEach(p => {
    p.categorySlug = categorySlugs[p.category];
});
const discountCodes = [
    { code: 'sale10', type: 'GiamPhanTram', value: 0.10, rank: 'Bronze', description: 'Giảm 10% tổng giá trị đơn hàng' },
    { code: 'freeship', type: 'MienPhiVanChuyen', value: 30000, rank: 'Silver', description: 'Miễn phí vận chuyển' },
    { code: 'giam50k', type: 'GiamTienMat', value: 50000, rank: 'Gold', description: 'Giảm trực tiếp 50.000đ' },
    { code: 'le2025', type: 'SieuSaleNgayLe', value: 0.20, rank: 'Bronze', description: 'Giảm 20% nhân dịp lễ' }
];